# This is a basic workflow to help you get started with Actions

name: Run Selenium Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      # Create a dropdown for options
      environment:
        description: 'Select an environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - production

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '22'  # Use the Java version your project requires
          distribution: 'adopt'

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # - name: Build with Maven
      #   run: mvn clean package

      - name: Run TestNG Tests
        run: mvn test -DsuiteXmlFile=testng.xml  # Adjust the path if necessary

      - name: Print selected environment
        run: echo "Selected environment: ${{ github.event.inputs.environment }}"

      # Conditionally run steps based on the dropdown selection
      - name: Run in development environment
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: echo "Running in development environment!"

      - name: Run in staging environment
        if: ${{ github.event.inputs.environment == 'staging' }}
        run: echo "Running in staging environment!"

      - name: Run in production environment
        if: ${{ github.event.inputs.environment == 'production' }}
        run: echo "Running in production environment!"
